### ISSUE TITLE
Some issues/suggestions

### ISSUE THREAD

**Issue by modernsnipe14** [braukStauter/FLRPServ#2]
- No server restart notification
- Garbage truck icon stays on mini map no matter the distance
- Gas glitches occasionally
- Number ID's over head instead of names
- OEM Tahoe
- Fire Cars won't spawn

**Comment by braukStauter** [comment]
**Update on this**
I am away from my workstation until Saturday so no dev will happen until then. I will update this thread when I complete everything but everything seems doable.

**Comment by braukStauter** [comment]
- Server restart notifications implemented at 5 mins.
- Cannot fix gas glitch, will try to find another alternative.
- Number ID's implemented..
- OEM Tahoe and Fire Cars are being worked on by Chase.

**Comment by braukStauter** [comment]
Garbage Truck icon removed.
