### ISSUE TITLE
Bugs Found

### ISSUE THREAD

**Issue by LoreMaggi** [braukStauter/FLRPServ#5]
Bug 1 : Near the Strenght training there is a garage when you take out a car you spawn  with car in the first floor of the house and you are locked in until you die or policeman help you.
Bug 2: When you customize your car and you store them dont save any customization and when you pick up the car its normal like when you buy them.
Bug 3: Pills from the 3 marker are disabled for citizien i think because i tried on all 3 (eccept hospital i didn't found entrance) and i was unable to buy (no menu appears)
Bug 4: when you choice your airstyle colour change somethimes.
Bug 5: When you use fix haircut thei put hairstyle like when you create character also when you use save on your house
12.23.17 last bug found : if you store a car out of fuel all cars on the garage when you take them out is out of fuel also if thei was full !

**Comment by braukStauter** [comment]
**Bug 1:** You need to go to K>Vehicle>Lock/Unlock. Boom. Done.
**Bug 2:** I am working on implementing a garage script. I will reply to this thread when completed.
**Bug 3:** Those are only accessible to EMS. In real life you cannot get pain medications without either a doctor or EMS. This will remain and not be changed.
**Bug 4:** You can change color in the barber shop.
**Bug 5:** Honestly cannot make out what that is trying to say.
**Bug 6:** There is currently no other fuel script available that works well with vRP and our economy system, as mentioned in another bug report. I will have to remove it completely if it continues to create issues.
